// Bộ icon Phosphor, tái xuất dưới tên Lucide cũ để chỉ cần đổi nguồn import là chạy.
// Phong cách Phosphor (bo tròn, nhiều weight) - khác hẳn Lucide, bớt cảm giác "mặc định AI".
export {
  Warning as AlertTriangle,
  TextAlignCenter as AlignCenter,
  TextAlignLeft as AlignLeft,
  TextAlignRight as AlignRight,
  Archive,
  ArrowDown, ArrowRight, ArrowUp,
  Medal as Award,
  TextB as Bold,
  Buildings as Building2,
  CalendarDots as CalendarClock,
  Camera, Check,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Circle,
  CheckCircle as CircleCheck,
  Circle as CircleDot,
  ClipboardText as ClipboardEdit,
  ClipboardText as ClipboardList,
  Clock, Copy,
  DownloadSimple as Download,
  PencilSimple as Edit3,
  Eraser,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  Factory,
  NotePencil as FileEdit,
  FilePlus as FilePlus2,
  FileText,
  TreeStructure as FolderTree,
  Gauge, GitBranch, Globe,
  ClockCounterClockwise as History,
  House as Home,
  Image, Tray as Inbox, Info,
  TextItalic as Italic,
  Stack as Layers,
  SquaresFour as LayoutDashboard,
  Rows as LayoutList,
  LinkSimple as Link2,
  ListBullets as List,
  ListChecks,
  ListNumbers as ListOrdered,
  CircleNotch as Loader2,
  Lock,
  SignOut as LogOut,
  Envelope as Mail,
  MapTrifold as Map,
  MapPin,
  Flag as Milestone,
  Minus, Moon,
  NavigationArrow as Navigation,
  ShareNetwork as Network,
  Package, Pause,
  PencilSimple as Pencil,
  Play, Plus, Printer, QrCode,
  ArrowArcRight as Redo2,
  Rocket,
  ArrowCounterClockwise as RotateCcw,
  Path as Route,
  Ruler,
  Scan as ScanLine,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  SkipBack, SkipForward,
  Sparkle as Sparkles,
  Sun, Tag,
  Trash as Trash2,
  TextUnderline as Underline,
  ArrowArcLeft as Undo2,
  CloudArrowUp as UploadCloud,
  User, UserPlus, Users,
  FlowArrow as Workflow,
  X, XCircle,
} from '@phosphor-icons/react';
